'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { Blend, Brush, Crop, Download, Droplets, Eraser, Eye, EyeOff, Focus, ImagePlus, Layers, MousePointer2, PaintBucket, Plus, Redo2, ScanSearch, Scissors, Shapes, Sparkles, Trash2, Type, Undo2, WandSparkles, X, ZoomIn, ZoomOut } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Slider } from '@/components/ui/slider';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuShortcut, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';

const Mask = Focus;

type Tool = 'move'|'marquee'|'smart'|'crop'|'brush'|'eraser'|'fill'|'gradient'|'text'|'shape'|'zoom';
type BlendMode = 'source-over'|'multiply'|'screen'|'overlay'|'darken'|'lighten';
type Rect = { x:number;y:number;w:number;h:number };
type LayerMeta = { id:string;name:string;visible:boolean;opacity:number;blend:BlendMode;x:number;y:number;hasMask:boolean;maskEnabled:boolean;locked?:boolean;rotation?:number;scaleX?:number;scaleY?:number;brightness?:number;contrast?:number;saturation?:number;blur?:number };
type LayerSurface = { pixels:HTMLCanvasElement;mask?:HTMLCanvasElement };
type Snapshot = { label:string;w:number;h:number;layers:LayerMeta[];surfaces:{id:string;pixels:ImageData;mask?:ImageData}[];selectedId:string };
type EditorDocument = { id:string;name:string;saved:boolean;doc:{w:number;h:number};layers:LayerMeta[];surfaces:Map<string,LayerSurface>;selectedId:string;history:Snapshot[];historyIndex:number;zoom:number;selection:Rect|null };

const toolItems:{id:Tool;label:string;key:string;icon:typeof Brush}[]=[
  {id:'move',label:'Move',key:'V',icon:MousePointer2},{id:'marquee',label:'Marquee select',key:'M',icon:ScanSearch},{id:'smart',label:'Smart select',key:'W',icon:WandSparkles},{id:'crop',label:'Crop',key:'C',icon:Crop},{id:'brush',label:'Brush',key:'B',icon:Brush},{id:'eraser',label:'Eraser',key:'E',icon:Eraser},{id:'fill',label:'Fill',key:'G',icon:PaintBucket},{id:'gradient',label:'Gradient',key:'D',icon:Droplets},{id:'text',label:'Text',key:'T',icon:Type},{id:'shape',label:'Rectangle',key:'U',icon:Shapes},{id:'zoom',label:'Zoom',key:'Z',icon:ZoomIn},
];
const blendLabels:Record<BlendMode,string>={'source-over':'Normal',multiply:'Multiply',screen:'Screen',overlay:'Overlay',darken:'Darken',lighten:'Lighten'};
const makeCanvas=(w:number,h:number)=>{const c=document.createElement('canvas');c.width=w;c.height=h;return c};
const cloneData=(d:ImageData)=>new ImageData(new Uint8ClampedArray(d.data),d.width,d.height);
const maskToAlpha=(mask:HTMLCanvasElement)=>{const out=makeCanvas(mask.width,mask.height),ctx=out.getContext('2d')!,source=mask.getContext('2d',{willReadFrequently:true})!.getImageData(0,0,mask.width,mask.height);for(let i=0;i<source.data.length;i+=4){source.data[i+3]=(source.data[i]+source.data[i+1]+source.data[i+2])/3;source.data[i]=source.data[i+1]=source.data[i+2]=255}ctx.putImageData(source,0,0);return out};
const sliderNumber=(value:number|readonly number[])=>Number(Array.isArray(value)?value[0]:value);
const drawLayer=(ctx:CanvasRenderingContext2D,layer:LayerMeta,surface:LayerSurface,w:number,h:number)=>{let source=surface.pixels;if(layer.hasMask&&layer.maskEnabled&&surface.mask){const temp=makeCanvas(w,h),tc=temp.getContext('2d')!;tc.drawImage(surface.pixels,0,0);tc.globalCompositeOperation='destination-in';tc.drawImage(maskToAlpha(surface.mask),0,0);source=temp}ctx.save();ctx.globalAlpha=layer.opacity/100;ctx.globalCompositeOperation=layer.blend;ctx.filter=`brightness(${layer.brightness??100}%) contrast(${layer.contrast??100}%) saturate(${layer.saturation??100}%) blur(${layer.blur??0}px)`;ctx.translate(layer.x+w/2,layer.y+h/2);ctx.rotate((layer.rotation??0)*Math.PI/180);ctx.scale(layer.scaleX??1,layer.scaleY??1);ctx.drawImage(source,-w/2,-h/2);ctx.restore()};

export default function Home(){
  const displayRef=useRef<HTMLCanvasElement>(null); const fileRef=useRef<HTMLInputElement>(null); const surfacesRef=useRef(new Map<string,LayerSurface>()); const layersRef=useRef<LayerMeta[]>([]);
  const drawing=useRef(false); const start=useRef({x:0,y:0}); const last=useRef({x:0,y:0}); const moveOrigin=useRef({x:0,y:0}); const historyRef=useRef<Snapshot[]>([]); const historyIndex=useRef(-1);
  const [doc,setDoc]=useState({w:1200,h:800}); const [layers,setLayers]=useState<LayerMeta[]>([]); const [selectedId,setSelectedId]=useState(''); const selectedRef=useRef(''); const [,setHistoryVersion]=useState(0);
  const [editing,setEditing]=useState<'pixels'|'mask'>('pixels'); const [tool,setTool]=useState<Tool>('move'); const [size,setSize]=useState(32); const [opacity,setOpacity]=useState(100); const [color,setColor]=useState('#171717'); const [zoom,setZoom]=useState(68); const [selection,setSelection]=useState<Rect|null>(null); const selectionRef=useRef<Rect|null>(null); const [dragRect,setDragRect]=useState<Rect|null>(null); const [text,setText]=useState('Your text'); const [fontSize,setFontSize]=useState(64); const [fileName,setFileName]=useState('Untitled artwork'); const [saved,setSaved]=useState(true); const [status,setStatus]=useState('Ready'); const [aiBusy,setAiBusy]=useState(false);
  const firstDocumentId=useRef(crypto.randomUUID()); const activeDocumentRef=useRef(firstDocumentId.current); const documentStoreRef=useRef(new Map<string,EditorDocument>()); const [activeDocumentId,setActiveDocumentId]=useState(firstDocumentId.current); const [documents,setDocuments]=useState<{id:string;name:string;saved:boolean}[]>([{id:firstDocumentId.current,name:'Untitled artwork',saved:true}]);

  const syncLayers=(next:LayerMeta[])=>{layersRef.current=next;setLayers(next)}; const select=(id:string)=>{selectedRef.current=id;setSelectedId(id)};
  const render=useCallback(()=>{const out=displayRef.current;if(!out)return;if(out.width!==doc.w)out.width=doc.w;if(out.height!==doc.h)out.height=doc.h;const ctx=out.getContext('2d')!;ctx.clearRect(0,0,doc.w,doc.h);for(const layer of [...layersRef.current].reverse()){if(!layer.visible)continue;const surface=surfacesRef.current.get(layer.id);if(surface)drawLayer(ctx,layer,surface,doc.w,doc.h)}},[doc]);
  useEffect(()=>{render()},[layers,render]); useEffect(()=>{selectionRef.current=selection},[selection]);
  const snapshot=useCallback((label:string)=>{const first=surfacesRef.current.values().next().value as LayerSurface|undefined;const snap:Snapshot={label,w:first?.pixels.width??1200,h:first?.pixels.height??800,layers:layersRef.current.map(x=>({...x})),selectedId:selectedRef.current,surfaces:layersRef.current.map(meta=>{const s=surfacesRef.current.get(meta.id)!;return{id:meta.id,pixels:cloneData(s.pixels.getContext('2d',{willReadFrequently:true})!.getImageData(0,0,s.pixels.width,s.pixels.height)),mask:s.mask?cloneData(s.mask.getContext('2d',{willReadFrequently:true})!.getImageData(0,0,s.mask.width,s.mask.height)):undefined}})};historyRef.current=historyRef.current.slice(0,historyIndex.current+1);historyRef.current.push(snap);if(historyRef.current.length>16)historyRef.current.shift();historyIndex.current=historyRef.current.length-1;setSaved(false);setHistoryVersion(v=>v+1)},[]);
  const restoreSnapshot=useCallback((index:number)=>{const snap=historyRef.current[index];if(!snap)return;const nextMap=new Map<string,LayerSurface>();for(const item of snap.surfaces){const pixels=makeCanvas(snap.w,snap.h);pixels.getContext('2d')!.putImageData(cloneData(item.pixels),0,0);let mask:HTMLCanvasElement|undefined;if(item.mask){mask=makeCanvas(snap.w,snap.h);mask.getContext('2d')!.putImageData(cloneData(item.mask),0,0)}nextMap.set(item.id,{pixels,mask})}surfacesRef.current=nextMap;setDoc({w:snap.w,h:snap.h});syncLayers(snap.layers.map(x=>({...x})));select(snap.selectedId);historyIndex.current=index;setStatus(snap.label);setHistoryVersion(v=>v+1)},[]);
  const undo=useCallback(()=>{if(historyIndex.current>0)restoreSnapshot(historyIndex.current-1)},[restoreSnapshot]);const redo=useCallback(()=>{if(historyIndex.current<historyRef.current.length-1)restoreSnapshot(historyIndex.current+1)},[restoreSnapshot]);
  const patchLayer=(id:string,patch:Partial<LayerMeta>,record?:string)=>{const next=layersRef.current.map(x=>x.id===id?{...x,...patch}:x);syncLayers(next);if(record)setTimeout(()=>snapshot(record),0)};
  const createLayer=(name='Pixel layer',selectIt=true)=>{const id=crypto.randomUUID();surfacesRef.current.set(id,{pixels:makeCanvas(doc.w,doc.h)});const meta:LayerMeta={id,name,visible:true,opacity:100,blend:'source-over',x:0,y:0,hasMask:false,maskEnabled:true};syncLayers([meta,...layersRef.current]);if(selectIt)select(id);setEditing('pixels');setTimeout(()=>snapshot('New layer'),0);return id};
  const init=useCallback(()=>{const bgId=crypto.randomUUID(),artId=crypto.randomUUID();const bg=makeCanvas(1200,800),b=bg.getContext('2d')!;b.fillStyle='#f4f4f1';b.fillRect(0,0,1200,800);const art=makeCanvas(1200,800),a=art.getContext('2d')!;const g=a.createLinearGradient(140,130,1060,680);g.addColorStop(0,'#5659ec');g.addColorStop(.52,'#9b5de5');g.addColorStop(1,'#fa8b72');a.fillStyle=g;a.beginPath();a.roundRect(120,110,960,580,52);a.fill();a.globalAlpha=.16;a.fillStyle='#fff';a.beginPath();a.arc(900,235,180,0,Math.PI*2);a.fill();a.beginPath();a.arc(315,580,245,0,Math.PI*2);a.fill();a.globalAlpha=1;a.fillStyle='#fff';a.font='600 74px Arial';a.fillText('Make something',205,378);a.font='32px Arial';a.fillStyle='rgba(255,255,255,.82)';a.fillText('Every layer is editable.',210,438);surfacesRef.current=new Map([[artId,{pixels:art}],[bgId,{pixels:bg}]]);const next:LayerMeta[]=[{id:artId,name:'Artwork',visible:true,opacity:100,blend:'source-over',x:0,y:0,hasMask:false,maskEnabled:true},{id:bgId,name:'Background',visible:true,opacity:100,blend:'source-over',x:0,y:0,hasMask:false,maskEnabled:true}];layersRef.current=next;setLayers(next);selectedRef.current=artId;setSelectedId(artId);setTimeout(()=>{snapshot('Open document');documentStoreRef.current.set(activeDocumentRef.current,{id:activeDocumentRef.current,name:'Untitled artwork',saved:false,doc:{w:1200,h:800},layers:layersRef.current,surfaces:surfacesRef.current,selectedId:selectedRef.current,history:historyRef.current,historyIndex:historyIndex.current,zoom:68,selection:null})},0)},[snapshot]);
  useEffect(()=>{init()},[init]);

  const persistActiveDocument=()=>{const id=activeDocumentRef.current;documentStoreRef.current.set(id,{id,name:fileName,saved,doc:{...doc},layers:layersRef.current,surfaces:surfacesRef.current,selectedId:selectedRef.current,history:historyRef.current,historyIndex:historyIndex.current,zoom,selection:selectionRef.current})};
  const loadDocument=(next:EditorDocument)=>{activeDocumentRef.current=next.id;setActiveDocumentId(next.id);surfacesRef.current=next.surfaces;layersRef.current=next.layers;setLayers(next.layers);selectedRef.current=next.selectedId;setSelectedId(next.selectedId);historyRef.current=next.history;historyIndex.current=next.historyIndex;setDoc(next.doc);setZoom(next.zoom);setSelection(next.selection);selectionRef.current=next.selection;setFileName(next.name);setSaved(next.saved);setEditing('pixels');setDragRect(null);setStatus(`Switched to ${next.name}`);setHistoryVersion(v=>v+1)};
  const switchDocument=(id:string)=>{if(id===activeDocumentRef.current)return;persistActiveDocument();const next=documentStoreRef.current.get(id);if(next)loadDocument(next)};
  const makeBlankDocument=()=>{persistActiveDocument();const id=crypto.randomUUID(),layerId=crypto.randomUUID(),pixels=makeCanvas(1200,800),ctx=pixels.getContext('2d')!;ctx.fillStyle='white';ctx.fillRect(0,0,1200,800);const nextLayers:LayerMeta[]=[{id:layerId,name:'Background',visible:true,opacity:100,blend:'source-over',x:0,y:0,hasMask:false,maskEnabled:true}];const snap:Snapshot={label:'New document',w:1200,h:800,layers:nextLayers.map(x=>({...x})),selectedId:layerId,surfaces:[{id:layerId,pixels:cloneData(ctx.getImageData(0,0,1200,800))}]};const next:EditorDocument={id,name:'Untitled artwork',saved:false,doc:{w:1200,h:800},layers:nextLayers,surfaces:new Map([[layerId,{pixels}]]),selectedId:layerId,history:[snap],historyIndex:0,zoom:68,selection:null};documentStoreRef.current.set(id,next);setDocuments(items=>[...items,{id,name:next.name,saved:false}]);loadDocument(next)};
  const closeDocument=(id:string)=>{const meta=documents.find(x=>x.id===id);const isActive=id===activeDocumentRef.current;if(isActive)persistActiveDocument();if(meta&&!meta.saved&&!window.confirm(`Close “${meta.name}” without exporting it?`))return;const remaining=documents.filter(x=>x.id!==id);documentStoreRef.current.delete(id);if(remaining.length===0){const layerId=crypto.randomUUID(),pixels=makeCanvas(1200,800),ctx=pixels.getContext('2d')!;ctx.fillStyle='white';ctx.fillRect(0,0,1200,800);const nextId=crypto.randomUUID(),nextLayers:LayerMeta[]=[{id:layerId,name:'Background',visible:true,opacity:100,blend:'source-over',x:0,y:0,hasMask:false,maskEnabled:true}],snap:Snapshot={label:'New document',w:1200,h:800,layers:nextLayers,selectedId:layerId,surfaces:[{id:layerId,pixels:cloneData(ctx.getImageData(0,0,1200,800))}]},next:EditorDocument={id:nextId,name:'Untitled artwork',saved:false,doc:{w:1200,h:800},layers:nextLayers,surfaces:new Map([[layerId,{pixels}]]),selectedId:layerId,history:[snap],historyIndex:0,zoom:68,selection:null};documentStoreRef.current.set(nextId,next);setDocuments([{id:nextId,name:next.name,saved:false}]);loadDocument(next);return}setDocuments(remaining);if(isActive){const index=Math.max(0,documents.findIndex(x=>x.id===id)-1),next=documentStoreRef.current.get(remaining[Math.min(index,remaining.length-1)].id);if(next)loadDocument(next)}};
  const renameDocument=(id:string)=>{if(id===activeDocumentRef.current)persistActiveDocument();const current=documentStoreRef.current.get(id),fallback=documents.find(x=>x.id===id)?.name;if(!current&&!fallback)return;const name=window.prompt('Document name',current?.name||fallback)?.trim();if(!name)return;if(current)current.name=name;setDocuments(items=>items.map(x=>x.id===id?{...x,name}:x));if(id===activeDocumentRef.current)setFileName(name)};
  useEffect(()=>{setDocuments(items=>items.map(x=>x.id===activeDocumentId?{...x,name:fileName,saved}:x))},[activeDocumentId,fileName,saved]);

  const point=(e:React.PointerEvent<HTMLCanvasElement>)=>{const c=displayRef.current!,r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}};
  const selected=()=>layersRef.current.find(x=>x.id===selectedRef.current); const targetContext=()=>{const meta=selected(),surface=meta&&surfacesRef.current.get(meta.id);if(!meta||!surface||meta.locked)return null;if(editing==='mask'&&surface.mask)return{ctx:surface.mask.getContext('2d')!,meta};return{ctx:surface.pixels.getContext('2d')!,meta}};
  const withSelection=(ctx:CanvasRenderingContext2D,fn:()=>void)=>{ctx.save();const s=selectionRef.current;if(s){ctx.beginPath();ctx.rect(s.x,s.y,s.w,s.h);ctx.clip()}fn();ctx.restore()};
  const begin=(e:React.PointerEvent<HTMLCanvasElement>)=>{const p=point(e),meta=selected();start.current=p;last.current=p;drawing.current=true;e.currentTarget.setPointerCapture(e.pointerId);if(meta)moveOrigin.current={x:meta.x,y:meta.y};if(tool==='fill'){fill();drawing.current=false}if(tool==='text'){placeText(p);drawing.current=false}if(tool==='smart'){smartSelect(p);drawing.current=false}if(tool==='zoom'){setZoom(z=>Math.min(200,z+12));drawing.current=false}};
  const move=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!drawing.current)return;const p=point(e);if(tool==='brush'||tool==='eraser'){const target=targetContext();if(!target)return;const local={x:p.x-target.meta.x,y:p.y-target.meta.y},prev={x:last.current.x-target.meta.x,y:last.current.y-target.meta.y};withSelection(target.ctx,()=>{target.ctx.globalAlpha=opacity/100;target.ctx.lineCap='round';target.ctx.lineJoin='round';target.ctx.lineWidth=size;if(editing==='mask'){target.ctx.globalCompositeOperation='source-over';target.ctx.strokeStyle=tool==='eraser'?'white':'black'}else{target.ctx.globalCompositeOperation=tool==='eraser'?'destination-out':'source-over';target.ctx.strokeStyle=color}target.ctx.beginPath();target.ctx.moveTo(prev.x,prev.y);target.ctx.lineTo(local.x,local.y);target.ctx.stroke()});last.current=p;render()}else if(tool==='move'){const meta=selected();if(meta&&!meta.locked)patchLayer(meta.id,{x:Math.round(moveOrigin.current.x+p.x-start.current.x),y:Math.round(moveOrigin.current.y+p.y-start.current.y)})}else if(['marquee','lasso','crop','shape','gradient'].includes(tool)){setDragRect({x:Math.min(start.current.x,p.x),y:Math.min(start.current.y,p.y),w:Math.abs(p.x-start.current.x),h:Math.abs(p.y-start.current.y)})}};
  const end=()=>{if(!drawing.current)return;drawing.current=false;if(tool==='brush'||tool==='eraser'||tool==='move')snapshot(tool==='move'?'Move layer':editing==='mask'?'Paint mask':tool==='eraser'?'Erase':'Brush stroke');if(tool==='marquee'||tool==='lasso'||tool==='crop'){if(dragRect&&dragRect.w>2&&dragRect.h>2)setSelection(dragRect);setDragRect(null)}if(tool==='shape'&&dragRect){shape(dragRect);setDragRect(null)}if(tool==='gradient'&&dragRect){applyGradient(dragRect);setDragRect(null)}render();setStatus('Ready')};

  const fill=()=>{const target=targetContext();if(!target)return;withSelection(target.ctx,()=>{target.ctx.globalAlpha=opacity/100;target.ctx.fillStyle=editing==='mask'?'black':color;target.ctx.fillRect(-target.meta.x,-target.meta.y,doc.w,doc.h)});snapshot(editing==='mask'?'Fill mask':'Fill');render()};
  const shape=(r:Rect)=>{const target=targetContext();if(!target)return;target.ctx.save();target.ctx.globalAlpha=opacity/100;target.ctx.strokeStyle=editing==='mask'?'black':color;target.ctx.lineWidth=size;target.ctx.strokeRect(r.x-target.meta.x,r.y-target.meta.y,r.w,r.h);target.ctx.restore();snapshot('Rectangle');render()};
  const applyGradient=(r:Rect)=>{const target=targetContext();if(!target)return;const g=target.ctx.createLinearGradient(r.x-target.meta.x,r.y-target.meta.y,r.x+r.w-target.meta.x,r.y+r.h-target.meta.y);g.addColorStop(0,color);g.addColorStop(1,'rgba(255,255,255,0)');withSelection(target.ctx,()=>{target.ctx.fillStyle=g;target.ctx.fillRect(r.x-target.meta.x,r.y-target.meta.y,r.w,r.h)});snapshot('Gradient');render()};
  const placeText=(p:{x:number;y:number})=>{const target=targetContext();if(!target||editing==='mask')return;target.ctx.save();target.ctx.fillStyle=color;target.ctx.globalAlpha=opacity/100;target.ctx.font=`600 ${fontSize}px Arial`;target.ctx.fillText(text,p.x-target.meta.x,p.y-target.meta.y);target.ctx.restore();snapshot('Text');render()};
  const smartSelect=(p:{x:number;y:number})=>{const surface=surfacesRef.current.get(selectedRef.current);if(!surface)return;const ctx=surface.pixels.getContext('2d',{willReadFrequently:true})!,data=ctx.getImageData(0,0,doc.w,doc.h),seedX=Math.max(0,Math.min(doc.w-1,Math.floor(p.x))),seedY=Math.max(0,Math.min(doc.h-1,Math.floor(p.y))),i=(seedY*doc.w+seedX)*4,base=[data.data[i],data.data[i+1],data.data[i+2]],seen=new Uint8Array(doc.w*doc.h),q:[[number,number]]=[[seedX,seedY]];let minX=seedX,maxX=seedX,minY=seedY,maxY=seedY,count=0;while(q.length&&count<180000){const [x,y]=q.pop()!,idx=y*doc.w+x;if(seen[idx])continue;seen[idx]=1;const k=idx*4,d=Math.abs(data.data[k]-base[0])+Math.abs(data.data[k+1]-base[1])+Math.abs(data.data[k+2]-base[2]);if(d>85)continue;minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);count++;if(x>0)q.push([x-1,y]);if(x<doc.w-1)q.push([x+1,y]);if(y>0)q.push([x,y-1]);if(y<doc.h-1)q.push([x,y+1])}setSelection({x:minX,y:minY,w:maxX-minX+1,h:maxY-minY+1});setStatus(`Selected ${count.toLocaleString()} connected pixels`)};
  const cropToSelection=()=>{const s=selectionRef.current;if(!s||s.w<2||s.h<2)return;const nw=Math.round(s.w),nh=Math.round(s.h);for(const meta of layersRef.current){const old=surfacesRef.current.get(meta.id)!;const pixels=makeCanvas(nw,nh);pixels.getContext('2d')!.drawImage(old.pixels,-s.x+meta.x,-s.y+meta.y);let mask:HTMLCanvasElement|undefined;if(old.mask){mask=makeCanvas(nw,nh);mask.getContext('2d')!.drawImage(old.mask,-s.x+meta.x,-s.y+meta.y)}surfacesRef.current.set(meta.id,{pixels,mask});meta.x=0;meta.y=0}setDoc({w:nw,h:nh});setSelection(null);selectionRef.current=null;setTimeout(()=>{snapshot('Crop');render()},0)};
  const selectAll=()=>setSelection({x:0,y:0,w:doc.w,h:doc.h});
  const addMask=()=>{const meta=selected();if(!meta)return;const surface=surfacesRef.current.get(meta.id)!;if(!surface.mask){surface.mask=makeCanvas(doc.w,doc.h);const ctx=surface.mask.getContext('2d')!;ctx.fillStyle='white';ctx.fillRect(0,0,doc.w,doc.h);patchLayer(meta.id,{hasMask:true,maskEnabled:true});}setEditing('mask');snapshot('Add layer mask');render()};
  const duplicate=()=>{const meta=selected(),surface=meta&&surfacesRef.current.get(meta.id);if(!meta||!surface)return;const id=crypto.randomUUID(),pixels=makeCanvas(doc.w,doc.h);pixels.getContext('2d')!.drawImage(surface.pixels,0,0);let mask:HTMLCanvasElement|undefined;if(surface.mask){mask=makeCanvas(doc.w,doc.h);mask.getContext('2d')!.drawImage(surface.mask,0,0)}surfacesRef.current.set(id,{pixels,mask});const copy={...meta,id,name:`${meta.name} copy`};syncLayers([copy,...layersRef.current]);select(id);snapshot('Duplicate layer');render()};
  const removeLayer=()=>{if(layersRef.current.length<=1)return;const id=selectedRef.current,next=layersRef.current.filter(x=>x.id!==id);surfacesRef.current.delete(id);syncLayers(next);select(next[0].id);snapshot('Delete layer');render()};
  const reorder=(dir:-1|1)=>{const i=layersRef.current.findIndex(x=>x.id===selectedRef.current),j=i+dir;if(i<0||j<0||j>=layersRef.current.length)return;const next=[...layersRef.current];[next[i],next[j]]=[next[j],next[i]];syncLayers(next);snapshot(dir<0?'Move layer up':'Move layer down');render()};
  const mergeDown=()=>{const i=layersRef.current.findIndex(x=>x.id===selectedRef.current);if(i<0||i>=layersRef.current.length-1)return;const upper=layersRef.current[i],lower=layersRef.current[i+1],upperSurface=surfacesRef.current.get(upper.id),lowerSurface=surfacesRef.current.get(lower.id);if(!upperSurface||!lowerSurface)return;const pixels=makeCanvas(doc.w,doc.h),ctx=pixels.getContext('2d')!;drawLayer(ctx,{...lower,blend:'source-over'},lowerSurface,doc.w,doc.h);drawLayer(ctx,upper,upperSurface,doc.w,doc.h);surfacesRef.current.set(lower.id,{pixels});surfacesRef.current.delete(upper.id);const merged={...lower,name:`${lower.name} + ${upper.name}`,opacity:100,blend:'source-over' as BlendMode,x:0,y:0,hasMask:false,rotation:0,scaleX:1,scaleY:1,brightness:100,contrast:100,saturation:100,blur:0};const next=layersRef.current.filter(x=>x.id!==upper.id).map(x=>x.id===lower.id?merged:x);syncLayers(next);select(lower.id);snapshot('Merge down');render()};
  const flattenImage=()=>{const pixels=makeCanvas(doc.w,doc.h),ctx=pixels.getContext('2d')!;for(const layer of [...layersRef.current].reverse()){const surface=surfacesRef.current.get(layer.id);if(layer.visible&&surface)drawLayer(ctx,layer,surface,doc.w,doc.h)}const id=crypto.randomUUID(),flat:LayerMeta={id,name:'Background',visible:true,opacity:100,blend:'source-over',x:0,y:0,hasMask:false,maskEnabled:true,locked:false};surfacesRef.current=new Map([[id,{pixels}]]);syncLayers([flat]);select(id);setEditing('pixels');snapshot('Flatten image');render()};
  const resetTransform=()=>{const meta=selected();if(meta)patchLayer(meta.id,{x:0,y:0,rotation:0,scaleX:1,scaleY:1},'Reset transform')};
  const resetAdjustments=()=>{const meta=selected();if(meta)patchLayer(meta.id,{brightness:100,contrast:100,saturation:100,blur:0},'Reset adjustments')};
  const removeMask=()=>{const meta=selected(),surface=meta&&surfacesRef.current.get(meta.id);if(!meta||!surface?.mask)return;delete surface.mask;patchLayer(meta.id,{hasMask:false},'Remove layer mask');setEditing('pixels');render()};
  const filter=(kind:'grayscale'|'invert'|'brightness'|'sharpen')=>{const target=targetContext();if(!target||editing==='mask')return;const ctx=target.ctx;if(kind==='sharpen'){ctx.save();ctx.filter='contrast(1.18) saturate(1.08)';ctx.drawImage(ctx.canvas,0,0);ctx.restore()}else{const d=ctx.getImageData(0,0,doc.w,doc.h);for(let i=0;i<d.data.length;i+=4){const r=d.data[i],g=d.data[i+1],b=d.data[i+2];if(kind==='grayscale'){const y=.299*r+.587*g+.114*b;d.data[i]=d.data[i+1]=d.data[i+2]=y}else if(kind==='invert'){d.data[i]=255-r;d.data[i+1]=255-g;d.data[i+2]=255-b}else{d.data[i]=Math.min(255,r*1.1+8);d.data[i+1]=Math.min(255,g*1.1+8);d.data[i+2]=Math.min(255,b*1.1+8)}}ctx.putImageData(d,0,0)}snapshot(kind[0].toUpperCase()+kind.slice(1));render()};
  const exportPng=useCallback(()=>{render();displayRef.current!.toBlob(blob=>{if(!blob){setStatus('Export failed');return}const url=URL.createObjectURL(blob),a=document.createElement('a');a.download=`${fileName.replace(/\.[^.]+$/,'')||'pixel-studio'}.png`;a.href=url;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setSaved(true);setStatus('PNG exported')},'image/png')},[fileName,render]);
  const openImage=(file?:File)=>{if(!file||!file.type.startsWith('image/'))return;const image=new Image();image.onload=()=>{persistActiveDocument();const w=image.naturalWidth,h=image.naturalHeight,documentId=crypto.randomUUID(),layerId=crypto.randomUUID(),pixels=makeCanvas(w,h);pixels.getContext('2d')!.drawImage(image,0,0);const name=file.name,nextLayers:LayerMeta[]=[{id:layerId,name:file.name.replace(/\.[^.]+$/,''),visible:true,opacity:100,blend:'source-over',x:0,y:0,hasMask:false,maskEnabled:true}],snap:Snapshot={label:'Open image',w,h,layers:nextLayers.map(x=>({...x})),selectedId:layerId,surfaces:[{id:layerId,pixels:cloneData(pixels.getContext('2d',{willReadFrequently:true})!.getImageData(0,0,w,h))}]},next:EditorDocument={id:documentId,name,saved:true,doc:{w,h},layers:nextLayers,surfaces:new Map([[layerId,{pixels}]]),selectedId:layerId,history:[snap],historyIndex:0,zoom:Math.min(100,Math.max(20,Math.round(760/w*100))),selection:null};documentStoreRef.current.set(documentId,next);setDocuments(items=>[...items,{id:documentId,name,saved:true}]);loadDocument(next);URL.revokeObjectURL(image.src);if(fileRef.current)fileRef.current.value=''};image.src=URL.createObjectURL(file)};
  const aiRemoveBackground=async()=>{const meta=selected(),surface=meta&&surfacesRef.current.get(meta.id);if(!meta||!surface||aiBusy)return;setAiBusy(true);setStatus('Loading free background-removal model…');try{const hf=await import('@huggingface/transformers');const remover=await hf.pipeline('background-removal','onnx-community/BEN2-ONNX');setStatus('AI is isolating the subject…');const output=await remover(surface.pixels.toDataURL('image/png')) as unknown as {data:Uint8Array;width:number;height:number};if(!output?.data)throw new Error('No image returned');const result=makeCanvas(output.width,output.height),rd=result.getContext('2d')!,bytes=new Uint8ClampedArray(output.data);rd.putImageData(new ImageData(bytes,output.width,output.height),0,0);const mask=makeCanvas(doc.w,doc.h),mc=mask.getContext('2d')!,scaled=makeCanvas(doc.w,doc.h),sc=scaled.getContext('2d')!;sc.drawImage(result,0,0,doc.w,doc.h);const data=sc.getImageData(0,0,doc.w,doc.h);for(let i=0;i<data.data.length;i+=4){const a=data.data[i+3];data.data[i]=data.data[i+1]=data.data[i+2]=a;data.data[i+3]=255}mc.putImageData(data,0,0);surface.mask=mask;patchLayer(meta.id,{hasMask:true,maskEnabled:true});setEditing('mask');snapshot('AI remove background');render();setStatus('Background removed — refine the mask with B/E')}catch{setStatus('AI model could not load. Try Auto Enhance or check the connection.')}finally{setAiBusy(false)}};

  useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options?:{signal?:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const life=new AbortController();void Promise.resolve(context.registerTool({name:'configure_editor_tool',title:'Configure editor tool',description:'Select a visible Pixel Studio tool and optionally configure brush size, opacity, and color.',inputSchema:{type:'object',properties:{tool:{type:'string',enum:['move','marquee','smart','crop','brush','eraser','fill','gradient','text','shape','zoom']},size:{type:'number',minimum:1,maximum:300},opacity:{type:'number',minimum:1,maximum:100},color:{type:'string',pattern:'^#[0-9a-fA-F]{6}$'}},required:['tool'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const value=input as {tool:Tool;size?:number;opacity?:number;color?:string};if(!toolItems.some(x=>x.id===value.tool))throw new Error('Unknown tool.');if(value.size!==undefined&&(!Number.isFinite(value.size)||value.size<1||value.size>300))throw new Error('Size must be between 1 and 300.');if(value.opacity!==undefined&&(!Number.isFinite(value.opacity)||value.opacity<1||value.opacity>100))throw new Error('Opacity must be between 1 and 100.');if(value.color!==undefined&&!/^#[0-9a-fA-F]{6}$/.test(value.color))throw new Error('Color must be a six-digit hex value.');setTool(value.tool);if(value.size!==undefined)setSize(Math.round(value.size));if(value.opacity!==undefined)setOpacity(Math.round(value.opacity));if(value.color!==undefined)setColor(value.color);return{tool:value.tool,size:value.size,opacity:value.opacity,color:value.color}},},{signal:life.signal})).catch(()=>undefined);return()=>life.abort()},[]);

  useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(['INPUT','TEXTAREA'].includes((e.target as HTMLElement)?.tagName))return;const k=e.key.toLowerCase();if((e.metaKey||e.ctrlKey)&&k==='z'){e.preventDefault();e.shiftKey?redo():undo();return}if((e.metaKey||e.ctrlKey)&&k==='s'){e.preventDefault();exportPng();return}if((e.metaKey||e.ctrlKey)&&k==='n'){e.preventDefault();makeBlankDocument();return}if((e.metaKey||e.ctrlKey)&&k==='j'){e.preventDefault();duplicate();return}if((e.metaKey||e.ctrlKey)&&k==='e'){e.preventDefault();mergeDown();return}if(k==='[')setSize(v=>Math.max(1,v-4));if(k===']')setSize(v=>Math.min(300,v+4));if(k==='escape')setSelection(null);const found=toolItems.find(x=>x.key.toLowerCase()===k);if(found)setTool(found.id)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[duplicate,exportPng,redo,undo]);

  const menu=(label:string,items:{name?:string;action?:()=>void;shortcut?:string;separator?:boolean}[])=><DropdownMenu><DropdownMenuTrigger className="menu-trigger">{label}</DropdownMenuTrigger><DropdownMenuContent className="editor-menu">{items.map((x,i)=>x.separator?<DropdownMenuSeparator key={i}/>:<DropdownMenuItem key={x.name} onClick={x.action}>{x.name}{x.shortcut&&<DropdownMenuShortcut>{x.shortcut}</DropdownMenuShortcut>}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>;
  const active=selected(); const selectionStyle=selection?{left:`${selection.x/doc.w*100}%`,top:`${selection.y/doc.h*100}%`,width:`${selection.w/doc.w*100}%`,height:`${selection.h/doc.h*100}%`}:undefined;const dragStyle=dragRect?{left:`${dragRect.x/doc.w*100}%`,top:`${dragRect.y/doc.h*100}%`,width:`${dragRect.w/doc.w*100}%`,height:`${dragRect.h/doc.h*100}%`}:undefined;
  return <main className="editor-shell" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();openImage(e.dataTransfer.files[0])}}>
    <header className="app-bar"><div className="brand"><span className="brand-mark">P</span><strong>Pixel Studio</strong></div><nav className="menus" aria-label="Application menu">{menu('File',[{name:'New document',action:makeBlankDocument,shortcut:'⌘N'},{name:'Open image in new tab…',action:()=>fileRef.current?.click(),shortcut:'⌘O'},{separator:true},{name:'Export PNG',action:exportPng,shortcut:'⌘S'}])}{menu('Edit',[{name:'Undo',action:undo,shortcut:'⌘Z'},{name:'Redo',action:redo,shortcut:'⇧⌘Z'},{separator:true},{name:'Deselect',action:()=>setSelection(null),shortcut:'Esc'}])}{menu('Image',[{name:'Auto enhance',action:()=>filter('brightness')},{name:'Grayscale',action:()=>filter('grayscale')},{name:'Invert',action:()=>filter('invert')},{name:'Sharpen',action:()=>filter('sharpen')},{separator:true},{name:'Crop to selection',action:cropToSelection},{name:'Flatten image',action:flattenImage}])}{menu('Layer',[{name:'New layer',action:()=>createLayer()},{name:'Duplicate layer',action:duplicate,shortcut:'⌘J'},{name:'Add layer mask',action:addMask},{name:'Remove layer mask',action:removeMask},{separator:true},{name:'Rotate 90°',action:()=>{const m=selected();if(m)patchLayer(m.id,{rotation:(m.rotation??0)+90},'Rotate layer')}},{name:'Flip horizontal',action:()=>{const m=selected();if(m)patchLayer(m.id,{scaleX:-(m.scaleX??1)},'Flip horizontal')}},{name:'Flip vertical',action:()=>{const m=selected();if(m)patchLayer(m.id,{scaleY:-(m.scaleY??1)},'Flip vertical')}},{name:'Reset transform',action:resetTransform},{separator:true},{name:'Move layer up',action:()=>reorder(-1)},{name:'Move layer down',action:()=>reorder(1)},{name:'Merge down',action:mergeDown,shortcut:'⌘E'},{name:'Delete layer',action:removeLayer}])}{menu('Select',[{name:'Select all',action:selectAll,shortcut:'⌘A'},{name:'Deselect',action:()=>setSelection(null),shortcut:'Esc'},{name:'Smart connected area',action:()=>setTool('smart')}])}{menu('Filter',[{name:'AI Remove Background',action:aiRemoveBackground},{separator:true},{name:'Auto enhance',action:()=>filter('brightness')},{name:'Black & white',action:()=>filter('grayscale')},{name:'Invert colors',action:()=>filter('invert')},{name:'Sharpen',action:()=>filter('sharpen')},{name:'Reset layer adjustments',action:resetAdjustments}])}{menu('View',[{name:'Zoom in',action:()=>setZoom(z=>Math.min(200,z+10))},{name:'Zoom out',action:()=>setZoom(z=>Math.max(10,z-10))},{name:'Fit on screen',action:()=>setZoom(Math.min(90,Math.round(760/doc.w*100)))}])}</nav><div className="header-actions"><Button variant="ghost" size="icon-sm" aria-label="Undo" onClick={undo}><Undo2/></Button><Button variant="ghost" size="icon-sm" aria-label="Redo" onClick={redo}><Redo2/></Button><Button variant="secondary" size="sm" onClick={()=>fileRef.current?.click()}><ImagePlus/>Open</Button><Button size="sm" onClick={exportPng}><Download/>Export</Button><input ref={fileRef} hidden type="file" accept="image/*" onChange={e=>openImage(e.target.files?.[0])}/></div></header>
    <section className="options-bar"><span className="active-tool">{toolItems.find(x=>x.id===tool)?.label}</span>{['brush','eraser','shape'].includes(tool)&&<><label>Size <strong>{size}px</strong></label><Slider aria-label="Tool size" className="option-slider" min={1} max={300} value={size} onValueChange={v=>setSize(sliderNumber(v))}/><label>Opacity <strong>{opacity}%</strong></label><Slider aria-label="Tool opacity" className="option-slider" min={1} max={100} value={opacity} onValueChange={v=>setOpacity(sliderNumber(v))}/><label className="color-label">Color<input type="color" aria-label="Tool color" value={color} onChange={e=>setColor(e.target.value)}/></label></>}{tool==='text'&&<><label>Text<input className="text-option" value={text} onChange={e=>setText(e.target.value)}/></label><label>Size<input className="number-option" type="number" min="8" max="300" value={fontSize} onChange={e=>setFontSize(+e.target.value)}/></label></>}{tool==='crop'&&<Button size="sm" onClick={cropToSelection} disabled={!selection}>Apply crop</Button>}<span className="editing-pill">Editing: {editing==='mask'?'Layer mask':'Layer pixels'}</span><span className="options-hint">{active?.locked?'Layer locked':tool==='brush'?'[ ] size · paint directly':tool==='move'?'Drag to move the selected layer':'Drag on the canvas'}</span></section>
    <div className="workspace"><aside className="tool-rail" aria-label="Tools">{toolItems.map(({id,label,key,icon:Icon})=><Button key={id} variant="ghost" size="icon-lg" className={tool===id?'tool-button active':'tool-button'} aria-label={label} title={`${label} · ${key}`} onClick={()=>setTool(id)}><Icon/></Button>)}<div className="color-stack"><span style={{background:color}}/><span/></div></aside>
      <section className="canvas-area"><div className="document-tabs">{documents.map(item=><div key={item.id} className={item.id===activeDocumentId?'document-tab active':'document-tab'}><button className="tab-main" onClick={()=>switchDocument(item.id)} onDoubleClick={()=>renameDocument(item.id)} title="Double-click to rename"><span className={(item.id===activeDocumentId?saved:item.saved)?'saved':'unsaved'}/>{item.id===activeDocumentId?fileName:item.name}{item.id===activeDocumentId&&<span className="tab-meta"> @ {zoom}%</span>}</button><button className="tab-close" aria-label={`Close ${item.name}`} title="Close tab" onClick={()=>closeDocument(item.id)}><X/></button></div>)}<button className="new-document-tab" aria-label="New document tab" title="New document · ⌘N" onClick={makeBlankDocument}><Plus/></button></div><div className="canvas-stage"><div className="canvas-frame" style={{width:`${doc.w*zoom/100}px`,maxWidth:'calc(100vw - 455px)'}}><canvas ref={displayRef} width={doc.w} height={doc.h} onPointerDown={begin} onPointerMove={move} onPointerUp={end} onPointerCancel={end}/>{selection&&<div className="selection-box" style={selectionStyle}/>} {dragRect&&<div className="drag-box" style={dragStyle}/>}</div></div></section>
      <aside className="panel-rail"><section className="panel compact"><div className="panel-title"><span>Smart tools</span><Sparkles/></div><div className="smart-grid"><Button variant="secondary" size="sm" onClick={aiRemoveBackground} disabled={aiBusy}><Scissors/>{aiBusy?'Working…':'AI remove background'}</Button><Button variant="ghost" size="sm" onClick={()=>filter('brightness')}><Sparkles/>Auto enhance</Button><Button variant="ghost" size="sm" onClick={()=>filter('sharpen')}><Focus/>Sharpen</Button><Button variant="ghost" size="sm" onClick={()=>setTool('smart')}><ScanSearch/>Smart select</Button></div><p className="smart-note">AI runs in your browser. The free model downloads once; no image is uploaded by Pixel Studio.</p></section>
        <section className="panel grow"><Tabs defaultValue="layers" className="h-full"><TabsList variant="line" className="panel-tabs"><TabsTrigger value="layers">Layers</TabsTrigger><TabsTrigger value="properties">Properties</TabsTrigger><TabsTrigger value="history">History</TabsTrigger></TabsList>
          <TabsContent value="layers" className="panel-content"><div className="layer-controls"><Select value={active?.blend||'source-over'} onValueChange={v=>active&&patchLayer(active.id,{blend:v as BlendMode},'Blend mode')}><SelectTrigger size="sm"><Blend/><SelectValue/></SelectTrigger><SelectContent>{(Object.keys(blendLabels) as BlendMode[]).map(x=><SelectItem key={x} value={x}>{blendLabels[x]}</SelectItem>)}</SelectContent></Select><label>Opacity {active?.opacity??100}%</label><Slider aria-label="Layer opacity" min={0} max={100} value={active?.opacity??100} onValueChange={v=>active&&patchLayer(active.id,{opacity:sliderNumber(v)})} onValueCommitted={()=>active&&snapshot('Layer opacity')}/></div><div className="layers-list">{layers.map(layer=><div key={layer.id} className={layer.id===selectedId?'layer-row selected':'layer-row'} onClick={()=>{select(layer.id);setEditing('pixels')}}><button aria-label={layer.visible?'Hide layer':'Show layer'} onClick={e=>{e.stopPropagation();patchLayer(layer.id,{visible:!layer.visible},'Layer visibility')}}>{layer.visible?<Eye/>:<EyeOff/>}</button><div className="layer-thumb"><Layers/></div><div className="layer-name"><strong>{layer.name}{layer.locked?' · locked':''}</strong><small>{blendLabels[layer.blend]} · {layer.opacity}%</small></div>{layer.hasMask&&<button className={editing==='mask'&&layer.id===selectedId?'mask-thumb active':'mask-thumb'} title="Edit mask" onClick={e=>{e.stopPropagation();select(layer.id);setEditing('mask')}}><Mask/></button>}</div>)}</div><div className="layer-actions"><Button variant="ghost" size="icon-sm" title="New layer" onClick={()=>createLayer()}><Plus/></Button><Button variant="ghost" size="icon-sm" title="Add mask" onClick={addMask}><Mask/></Button><Button variant="ghost" size="icon-sm" title="Duplicate" onClick={duplicate}><Layers/></Button><Button variant="ghost" size="icon-sm" title={active?.locked?'Unlock layer':'Lock layer'} onClick={()=>active&&patchLayer(active.id,{locked:!active.locked},active.locked?'Unlock layer':'Lock layer')}><span className="action-glyph">{active?.locked?'◉':'◎'}</span></Button><Button variant="ghost" size="icon-sm" title="Merge down" onClick={mergeDown}><span className="action-glyph">⇣</span></Button><Button variant="ghost" size="icon-sm" title="Delete" onClick={removeLayer}><Trash2/></Button></div></TabsContent>
          <TabsContent value="properties" className="panel-content properties-panel"><div className="property-heading"><strong>Transform</strong><button onClick={resetTransform}>Reset</button></div><div className="transform-grid"><label>X<input type="number" value={active?.x??0} onChange={e=>active&&patchLayer(active.id,{x:+e.target.value})} onBlur={()=>active&&snapshot('Transform layer')}/></label><label>Y<input type="number" value={active?.y??0} onChange={e=>active&&patchLayer(active.id,{y:+e.target.value})} onBlur={()=>active&&snapshot('Transform layer')}/></label></div><label>Rotation <span>{active?.rotation??0}°</span></label><Slider aria-label="Layer rotation" min={-180} max={180} value={active?.rotation??0} onValueChange={v=>active&&patchLayer(active.id,{rotation:sliderNumber(v)})} onValueCommitted={()=>active&&snapshot('Rotate layer')}/><label>Scale <span>{Math.round((active?.scaleX??1)*100)}%</span></label><Slider aria-label="Layer scale" min={10} max={300} value={Math.abs(active?.scaleX??1)*100} onValueChange={v=>{if(!active)return;const n=sliderNumber(v)/100;patchLayer(active.id,{scaleX:(active.scaleX??1)<0?-n:n,scaleY:(active.scaleY??1)<0?-n:n})}} onValueCommitted={()=>active&&snapshot('Scale layer')}/><div className="property-buttons"><button onClick={()=>active&&patchLayer(active.id,{scaleX:-(active.scaleX??1)},'Flip horizontal')}>Flip H</button><button onClick={()=>active&&patchLayer(active.id,{scaleY:-(active.scaleY??1)},'Flip vertical')}>Flip V</button><button onClick={()=>active&&patchLayer(active.id,{rotation:(active.rotation??0)+90},'Rotate layer')}>Rotate 90°</button></div><div className="property-heading"><strong>Adjustments</strong><button onClick={resetAdjustments}>Reset</button></div>{([['Brightness','brightness',0,200],['Contrast','contrast',0,200],['Saturation','saturation',0,200],['Blur','blur',0,20]] as const).map(([label,key,min,max])=><div className="property-slider" key={key}><label>{label}<span>{active?.[key]??(key==='blur'?0:100)}{key==='blur'?'px':'%'}</span></label><Slider aria-label={`Layer ${label.toLowerCase()}`} min={min} max={max} step={key==='blur'?.5:1} value={active?.[key]??(key==='blur'?0:100)} onValueChange={v=>active&&patchLayer(active.id,{[key]:sliderNumber(v)})} onValueCommitted={()=>active&&snapshot(`${label} adjustment`)}/></div>)}</TabsContent>
          <TabsContent value="history" className="panel-content history-list">{historyRef.current.map((x,i)=><button key={`${x.label}-${i}`} className={i===historyIndex.current?'current':''} onClick={()=>restoreSnapshot(i)}>{x.label}</button>)}</TabsContent></Tabs></section></aside>
    </div><footer className="status-bar"><span>{status}</span><span className="status-center">{doc.w} × {doc.h}px · {layers.length} layers{selection?' · selection active':''}</span><div className="zoom-control"><Button variant="ghost" size="icon-xs" aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(10,z-10))}><ZoomOut/></Button><Slider aria-label="Canvas zoom" min={10} max={200} value={zoom} onValueChange={v=>setZoom(sliderNumber(v))}/><span>{zoom}%</span><Button variant="ghost" size="icon-xs" aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(200,z+10))}><ZoomIn/></Button></div></footer>
  </main>
}
