'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { Brush, Crop, Download, Eraser, Eye, EyeOff, Hand, ImagePlus, Lasso, MousePointer2, PaintBucket, Plus, Redo2, Shapes, SlidersHorizontal, Sparkles, Type, Undo2, WandSparkles, ZoomIn, ZoomOut } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Slider } from '@/components/ui/slider';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';

type Tool = 'move' | 'select' | 'brush' | 'eraser' | 'text' | 'shape' | 'crop' | 'hand';
const tools: { id: Tool; label: string; key: string; icon: typeof Brush }[] = [
  { id: 'move', label: 'Move', key: 'V', icon: MousePointer2 }, { id: 'select', label: 'Select', key: 'M', icon: Lasso },
  { id: 'brush', label: 'Brush', key: 'B', icon: Brush }, { id: 'eraser', label: 'Eraser', key: 'E', icon: Eraser },
  { id: 'text', label: 'Text', key: 'T', icon: Type }, { id: 'shape', label: 'Shape', key: 'U', icon: Shapes },
  { id: 'crop', label: 'Crop', key: 'C', icon: Crop }, { id: 'hand', label: 'Hand', key: 'H', icon: Hand },
];

export default function Home() {
  const canvasRef = useRef<HTMLCanvasElement>(null); const fileRef = useRef<HTMLInputElement>(null);
  const drawing = useRef(false); const lastPoint = useRef({ x: 0, y: 0 }); const history = useRef<ImageData[]>([]); const historyIndex = useRef(-1);
  const [tool, setTool] = useState<Tool>('brush'); const [size, setSize] = useState(24); const [opacity, setOpacity] = useState(100);
  const [color, setColor] = useState('#171717'); const [zoom, setZoom] = useState(72); const [visible, setVisible] = useState(true);
  const [fileName, setFileName] = useState('Untitled artwork'); const [saved, setSaved] = useState(true); const [status, setStatus] = useState('Ready');

  const pushHistory = useCallback(() => { const canvas = canvasRef.current; const ctx = canvas?.getContext('2d', { willReadFrequently: true }); if (!canvas || !ctx) return; history.current = history.current.slice(0, historyIndex.current + 1); history.current.push(ctx.getImageData(0, 0, canvas.width, canvas.height)); if (history.current.length > 24) history.current.shift(); historyIndex.current = history.current.length - 1; setSaved(false); }, []);
  const makeStarter = useCallback(() => { const canvas = canvasRef.current; const ctx = canvas?.getContext('2d', { willReadFrequently: true }); if (!canvas || !ctx) return; ctx.fillStyle = '#f7f7f5'; ctx.fillRect(0, 0, canvas.width, canvas.height); const gradient = ctx.createLinearGradient(160, 120, 1040, 690); gradient.addColorStop(0, '#5b5df0'); gradient.addColorStop(.52, '#9c62ed'); gradient.addColorStop(1, '#f98b72'); ctx.fillStyle = gradient; ctx.beginPath(); ctx.roundRect(120, 110, 960, 580, 52); ctx.fill(); ctx.globalAlpha = .16; ctx.fillStyle = '#fff'; ctx.beginPath(); ctx.arc(900, 235, 180, 0, Math.PI * 2); ctx.fill(); ctx.beginPath(); ctx.arc(315, 580, 245, 0, Math.PI * 2); ctx.fill(); ctx.globalAlpha = 1; ctx.fillStyle = '#fff'; ctx.font = '600 74px Arial'; ctx.fillText('Make something', 205, 378); ctx.font = '32px Arial'; ctx.fillStyle = 'rgba(255,255,255,.8)'; ctx.fillText('Your canvas is ready.', 210, 438); history.current = [ctx.getImageData(0, 0, canvas.width, canvas.height)]; historyIndex.current = 0; }, []);
  useEffect(() => { makeStarter(); }, [makeStarter]);
  const restore = useCallback((index: number) => { const canvas = canvasRef.current; const item = history.current[index]; if (!canvas || !item) return; canvas.getContext('2d')?.putImageData(item, 0, 0); historyIndex.current = index; setSaved(false); }, []);
  const undo = useCallback(() => { if (historyIndex.current > 0) restore(historyIndex.current - 1); }, [restore]);
  const redo = useCallback(() => { if (historyIndex.current < history.current.length - 1) restore(historyIndex.current + 1); }, [restore]);
  const exportPng = useCallback(() => { const canvas = canvasRef.current; if (!canvas) return; const link = document.createElement('a'); link.download = `${fileName.replace(/\.[^.]+$/, '') || 'pixel-studio'}.png`; link.href = canvas.toDataURL('image/png'); link.click(); setSaved(true); setStatus('PNG exported'); }, [fileName]);

  useEffect(() => { const onKey = (event: KeyboardEvent) => { const tag = (event.target as HTMLElement)?.tagName; if (tag === 'INPUT' || tag === 'TEXTAREA') return; const key = event.key.toLowerCase(); if ((event.metaKey || event.ctrlKey) && key === 'z') { event.preventDefault(); event.shiftKey ? redo() : undo(); return; } if ((event.metaKey || event.ctrlKey) && key === 's') { event.preventDefault(); exportPng(); return; } if (key === '[') setSize(v => Math.max(1, v - 4)); if (key === ']') setSize(v => Math.min(200, v + 4)); const found = tools.find(item => item.key.toLowerCase() === key); if (found) setTool(found.id); if (event.code === 'Space') setTool('hand'); }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, [exportPng, redo, undo]);
  useEffect(() => {
    const context = (document as Document & { modelContext?: { registerTool: (tool: unknown, options?: { signal?: AbortSignal }) => void | Promise<void> } }).modelContext;
    if (!context?.registerTool) return;
    const lifecycle = new AbortController();
    void Promise.resolve(context.registerTool({ name: 'configure_brush', title: 'Configure brush', description: 'Select the brush and set its size, opacity, and color in the visible editor.', inputSchema: { type: 'object', properties: { size: { type: 'number', minimum: 1, maximum: 200 }, opacity: { type: 'number', minimum: 1, maximum: 100 }, color: { type: 'string', pattern: '^#[0-9a-fA-F]{6}$' } }, additionalProperties: false }, annotations: { readOnlyHint: false, untrustedContentHint: false }, execute(input: unknown) { const value = input as { size?: number; opacity?: number; color?: string }; if (value.size !== undefined && (!Number.isFinite(value.size) || value.size < 1 || value.size > 200)) throw new Error('Brush size must be between 1 and 200.'); if (value.opacity !== undefined && (!Number.isFinite(value.opacity) || value.opacity < 1 || value.opacity > 100)) throw new Error('Opacity must be between 1 and 100.'); if (value.color !== undefined && !/^#[0-9a-fA-F]{6}$/.test(value.color)) throw new Error('Color must be a six-digit hex value.'); setTool('brush'); if (value.size !== undefined) setSize(Math.round(value.size)); if (value.opacity !== undefined) setOpacity(Math.round(value.opacity)); if (value.color !== undefined) setColor(value.color); return { tool: 'brush', size: value.size, opacity: value.opacity, color: value.color }; } }, { signal: lifecycle.signal })).catch(() => undefined);
    return () => lifecycle.abort();
  }, []);
  const canvasPoint = (event: React.PointerEvent<HTMLCanvasElement>) => { const canvas = canvasRef.current!; const rect = canvas.getBoundingClientRect(); return { x: (event.clientX - rect.left) * canvas.width / rect.width, y: (event.clientY - rect.top) * canvas.height / rect.height }; };
  const startDraw = (event: React.PointerEvent<HTMLCanvasElement>) => { if (tool !== 'brush' && tool !== 'eraser') return; drawing.current = true; lastPoint.current = canvasPoint(event); event.currentTarget.setPointerCapture(event.pointerId); };
  const draw = (event: React.PointerEvent<HTMLCanvasElement>) => { if (!drawing.current || (tool !== 'brush' && tool !== 'eraser')) return; const ctx = canvasRef.current!.getContext('2d')!; const point = canvasPoint(event); ctx.save(); ctx.globalAlpha = opacity / 100; ctx.globalCompositeOperation = tool === 'eraser' ? 'destination-out' : 'source-over'; ctx.strokeStyle = color; ctx.lineWidth = size; ctx.lineCap = 'round'; ctx.lineJoin = 'round'; ctx.beginPath(); ctx.moveTo(lastPoint.current.x, lastPoint.current.y); ctx.lineTo(point.x, point.y); ctx.stroke(); ctx.restore(); lastPoint.current = point; setStatus(tool === 'brush' ? 'Painting' : 'Erasing'); };
  const endDraw = () => { if (!drawing.current) return; drawing.current = false; pushHistory(); setStatus('Ready'); };
  const openImage = (file?: File) => { if (!file || !file.type.startsWith('image/')) return; const image = new Image(); image.onload = () => { const canvas = canvasRef.current!; canvas.width = image.naturalWidth; canvas.height = image.naturalHeight; const ctx = canvas.getContext('2d', { willReadFrequently: true })!; ctx.drawImage(image, 0, 0); setFileName(file.name); setZoom(Math.min(100, Math.round(760 / image.naturalWidth * 100))); history.current = [ctx.getImageData(0, 0, canvas.width, canvas.height)]; historyIndex.current = 0; setSaved(true); setStatus(`${image.naturalWidth} × ${image.naturalHeight}`); URL.revokeObjectURL(image.src); }; image.src = URL.createObjectURL(file); };

  return <main className="editor-shell" onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); openImage(e.dataTransfer.files[0]); }}>
    <header className="app-bar"><div className="brand"><span className="brand-mark">P</span><strong>Pixel Studio</strong></div><nav className="menus" aria-label="Application menu">{['File','Edit','Image','Layer','Select','Filter','View'].map(x => <button key={x}>{x}</button>)}</nav><div className="header-actions"><Button variant="ghost" size="icon-sm" aria-label="Undo" title="Undo · ⌘Z" onClick={undo}><Undo2 /></Button><Button variant="ghost" size="icon-sm" aria-label="Redo" title="Redo · ⇧⌘Z" onClick={redo}><Redo2 /></Button><Button variant="secondary" size="sm" onClick={() => fileRef.current?.click()}><ImagePlus /> Open</Button><Button size="sm" onClick={exportPng}><Download /> Export</Button><input ref={fileRef} hidden type="file" accept="image/*" onChange={e => openImage(e.target.files?.[0])} /></div></header>
    <section className="options-bar" aria-label="Tool options"><span className="active-tool">{tools.find(t => t.id === tool)?.label}</span>{(tool === 'brush' || tool === 'eraser') && <><label>Size <strong>{size}px</strong></label><Slider className="option-slider" min={1} max={200} value={[size]} onValueChange={v => setSize(v[0])} /><label>Opacity <strong>{opacity}%</strong></label><Slider className="option-slider" min={1} max={100} value={[opacity]} onValueChange={v => setOpacity(v[0])} /><label className="color-label">Color <input aria-label="Brush color" type="color" value={color} onChange={e => setColor(e.target.value)} /></label></>}<span className="options-hint">[ ] changes brush size</span></section>
    <div className="workspace"><aside className="tool-rail" aria-label="Tools">{tools.map(({ id, label, key, icon: Icon }) => <Button key={id} variant="ghost" size="icon-lg" className={tool === id ? 'tool-button active' : 'tool-button'} aria-label={`${label} tool`} title={`${label} · ${key}`} onClick={() => setTool(id)}><Icon /></Button>)}<div className="tool-divider" /><Button variant="ghost" size="icon-lg" className="tool-button" aria-label="Fill tool" title="Fill"><PaintBucket /></Button><Button variant="ghost" size="icon-lg" className="tool-button" aria-label="Magic selection" title="Magic selection"><WandSparkles /></Button><div className="color-stack" aria-label="Foreground and background colors"><span style={{ background: color }} /><span /></div></aside>
      <section className="canvas-area" aria-label="Canvas workspace"><div className="document-tabs"><button className="document-tab"><span className={saved ? 'saved' : 'unsaved'} /> {fileName}<span className="tab-meta"> @ {zoom}%</span></button></div><div className="canvas-stage"><div className="canvas-frame" style={{ width: `${1200 * zoom / 100}px`, maxWidth: 'calc(100vw - 430px)' }}><canvas ref={canvasRef} width={1200} height={800} style={{ opacity: visible ? 1 : 0 }} onPointerDown={startDraw} onPointerMove={draw} onPointerUp={endDraw} onPointerCancel={endDraw} /></div><div className="drop-note"><ImagePlus /> Drop an image anywhere to open it</div></div></section>
      <aside className="panel-rail"><section className="panel compact"><div className="panel-title"><span>Color</span><SlidersHorizontal /></div><div className="color-card"><input aria-label="Current color" type="color" value={color} onChange={e => setColor(e.target.value)} /><div><strong>{color.toUpperCase()}</strong><small>RGB color</small></div></div><div className="swatches">{['#171717','#ffffff','#ef4444','#f59e0b','#22c55e','#3b82f6','#8b5cf6','#ec4899'].map(c => <button key={c} aria-label={`Use ${c}`} style={{background:c}} onClick={() => setColor(c)} />)}</div></section><section className="panel grow"><Tabs defaultValue="layers" className="h-full"><TabsList variant="line" className="panel-tabs"><TabsTrigger value="layers">Layers</TabsTrigger><TabsTrigger value="history">History</TabsTrigger></TabsList><TabsContent value="layers" className="panel-content"><div className="layer-row selected"><button aria-label={visible ? 'Hide layer' : 'Show layer'} onClick={() => setVisible(!visible)}>{visible ? <Eye /> : <EyeOff />}</button><div className="layer-thumb"><Sparkles /></div><div><strong>Artwork</strong><small>Pixel layer</small></div></div><div className="layer-row"><Eye /><div className="layer-thumb white" /><div><strong>Background</strong><small>Locked</small></div></div><Button variant="ghost" size="sm" className="new-layer"><Plus /> New layer</Button></TabsContent><TabsContent value="history" className="panel-content history-list"><button onClick={makeStarter}>Open document</button>{history.current.length > 1 && <button onClick={undo}>Brush stroke</button>}<span>Current state</span></TabsContent></Tabs></section></aside>
    </div>
    <footer className="status-bar"><span>{status}</span><span className="status-center">1200 × 800 px · RGB</span><div className="zoom-control"><Button variant="ghost" size="icon-xs" aria-label="Zoom out" onClick={() => setZoom(v => Math.max(10, v - 10))}><ZoomOut /></Button><Slider min={10} max={160} value={[zoom]} onValueChange={v => setZoom(v[0])} /><span>{zoom}%</span><Button variant="ghost" size="icon-xs" aria-label="Zoom in" onClick={() => setZoom(v => Math.min(160, v + 10))}><ZoomIn /></Button></div></footer>
  </main>;
}
