'use client';
import {useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {encodeImage,type ExportFormat} from '@/lib/image-export';
export function ExportDialog({source,name,onClose}:{source:HTMLCanvasElement|null;name:string;onClose:()=>void}){
  const [format,setFormat]=useState<ExportFormat>('png'),[quality,setQuality]=useState(92),[scale,setScale]=useState(1),[matte,setMatte]=useState('transparent'),[busy,setBusy]=useState(false),[error,setError]=useState('');
  return <Dialog open={!!source} onOpenChange={open=>{if(!open&&!busy){setError('');onClose()}}}><DialogContent className="sm:max-w-lg" onKeyDown={e=>e.stopPropagation()}><DialogTitle>Export image</DialogTitle><DialogDescription>Exports the visible artwork. Save a layered project to keep editing.</DialogDescription><label className="grid gap-1">Format<select className="border rounded p-2 bg-background" value={format} onChange={e=>setFormat(e.target.value as ExportFormat)}>{['png','jpeg','webp','tiff','pdf'].map(f=><option key={f} value={f}>{f.toUpperCase()}</option>)}</select></label><label className="grid gap-1">Size<select className="border rounded p-2 bg-background" value={scale} onChange={e=>setScale(+e.target.value)}>{[.25,.5,1,2].map(s=><option key={s} value={s}>{s*100}%</option>)}</select></label><p>{source?Math.round(source.width*scale):0} × {source?Math.round(source.height*scale):0} pixels</p>{['jpeg','webp','pdf'].includes(format)&&<label className="grid gap-1">Quality<input className="border rounded p-2" type="number" min={1} max={100} value={quality} onChange={e=>setQuality(+e.target.value)}/></label>}<label className="grid gap-1">Background<select className="border rounded p-2 bg-background" value={matte} onChange={e=>setMatte(e.target.value)}><option value="transparent">Transparent (white for JPEG/PDF)</option><option value="#ffffff">White</option><option value="#000000">Black</option></select></label>{format==='pdf'&&<p>One flattened, JPEG-compressed page at 96 pixels per inch. No editable text, layers or print color profiles.</p>}{format==='tiff'&&<p>Uncompressed 8-bit RGBA TIFF. No layers or print color profiles.</p>}{error&&<p role="alert">{error}</p>}<Button disabled={busy||!Number.isFinite(quality)||quality<1||quality>100} onClick={async()=>{if(!source)return;setBusy(true);setError('');try{const blob=await encodeImage(source,format,quality,scale,matte),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(name.replace(/\.[^.]+$/,'')||'Artwork')+'.'+(format==='jpeg'?'jpg':format==='tiff'?'tif':format);a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);onClose()}catch(e){setError(e instanceof Error?e.message:'Export failed.')}finally{setBusy(false)}}}>{busy?'Exporting…':'Download image'}</Button></DialogContent></Dialog>;
}
