'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';

type Resampling='nearest'|'low'|'medium'|'high';
export function ImageSizeDialog({open,width,height,resolution,onClose,onApply}:{open:boolean;width:number;height:number;resolution:number;onClose:()=>void;onApply:(width:number,height:number,resampling:Resampling,resolution:number)=>void}){
 const [w,setW]=useState(width),[h,setH]=useState(height),[ppi,setPpi]=useState(resolution),[linked,setLinked]=useState(true),[resampling,setResampling]=useState<Resampling>('high');
 useEffect(()=>{if(open){setW(width);setH(height);setPpi(resolution)}},[open,width,height,resolution]);
 const valid=Number.isFinite(w)&&Number.isFinite(h)&&w>=1&&h>=1&&w<=16384&&h<=16384&&w*h<=64_000_000&&ppi>=1&&ppi<=2400;
 return <Dialog open={open} onOpenChange={v=>{if(!v)onClose()}}><DialogContent><DialogTitle>Image Size</DialogTitle><DialogDescription>Resize every layer and mask. Choose the interpolation that matches the artwork.</DialogDescription><div className="resize-fields"><label>Width (px)<input type="number" min={1} max={16384} value={w} onChange={e=>{const n=+e.target.value;setW(n);if(linked)setH(Math.max(1,Math.round(n*height/width)))}}/></label><label>Height (px)<input type="number" min={1} max={16384} value={h} onChange={e=>{const n=+e.target.value;setH(n);if(linked)setW(Math.max(1,Math.round(n*width/height)))}}/></label><label>Resolution (ppi)<input type="number" min={1} max={2400} value={ppi} onChange={e=>setPpi(+e.target.value)}/></label></div><label><input type="checkbox" checked={linked} onChange={e=>setLinked(e.target.checked)}/> Constrain proportions</label><label>Resampling<select value={resampling} onChange={e=>setResampling(e.target.value as Resampling)}><option value="nearest">Nearest neighbour — pixel art</option><option value="low">Low — fast</option><option value="medium">Bilinear</option><option value="high">Bicubic-quality</option></select></label><p>{valid?`${Math.round(w).toLocaleString()} × ${Math.round(h).toLocaleString()} pixels`:'Choose dimensions within the document limits.'}</p><div className="dialog-actions"><Button variant="outline" onClick={onClose}>Cancel</Button><Button disabled={!valid} onClick={()=>{onApply(Math.round(w),Math.round(h),resampling,ppi);onClose()}}>Resize</Button></div></DialogContent></Dialog>;
}

export function CanvasSizeDialog({open,width,height,onClose,onApply}:{open:boolean;width:number;height:number;onClose:()=>void;onApply:(width:number,height:number,anchorX:-1|0|1,anchorY:-1|0|1)=>void}){
 const [w,setW]=useState(width),[h,setH]=useState(height),[anchor,setAnchor]=useState<[number,number]>([0,0]);
 useEffect(()=>{if(open){setW(width);setH(height);setAnchor([0,0])}},[open,width,height]);
 const valid=Number.isFinite(w)&&Number.isFinite(h)&&w>=1&&h>=1&&w<=16384&&h<=16384&&w*h<=64_000_000;
 return <Dialog open={open} onOpenChange={v=>{if(!v)onClose()}}><DialogContent><DialogTitle>Canvas Size</DialogTitle><DialogDescription>Change the canvas without scaling layer pixels. The anchor keeps that side or corner fixed.</DialogDescription><div className="resize-fields"><label>Width (px)<input type="number" min={1} max={16384} value={w} onChange={e=>setW(+e.target.value)}/></label><label>Height (px)<input type="number" min={1} max={16384} value={h} onChange={e=>setH(+e.target.value)}/></label></div><fieldset><legend>Anchor</legend><div className="anchor-picker">{([-1,0,1] as const).flatMap(y=>([-1,0,1] as const).map(x=><button type="button" key={`${x}:${y}`} aria-label={`${y<0?'Top':y>0?'Bottom':'Middle'} ${x<0?'left':x>0?'right':'center'} anchor`} aria-pressed={anchor[0]===x&&anchor[1]===y} onClick={()=>setAnchor([x,y])}>{anchor[0]===x&&anchor[1]===y?'●':'○'}</button>))}</div></fieldset><div className="dialog-actions"><Button variant="outline" onClick={onClose}>Cancel</Button><Button disabled={!valid} onClick={()=>{onApply(Math.round(w),Math.round(h),anchor[0] as -1|0|1,anchor[1] as -1|0|1);onClose()}}>Resize canvas</Button></div></DialogContent></Dialog>;
}
