export type Guide={id:string;axis:'x'|'y';position:number};
export type RulerUnit='px'|'%'|'in'|'cm'|'mm';
export type EditorView={x:number;y:number;rotation:number;rulers:boolean;grid:boolean;snap:boolean;gridSize:number;units:RulerUnit;resolution:number;rulerOrigin:{x:number;y:number};guides:Guide[]};
export const defaultView:EditorView={x:0,y:0,rotation:0,rulers:false,grid:false,snap:false,gridSize:100,units:'px',resolution:72,rulerOrigin:{x:0,y:0},guides:[]};
export const clampZoom=(value:number)=>Math.max(1,Math.min(800,Math.round(value*10)/10));
export function readView(value:Partial<EditorView>|undefined):EditorView{const units:RulerUnit=['px','%','in','cm','mm'].includes(value?.units??'')?value!.units as RulerUnit:'px',origin=value?.rulerOrigin;return {...defaultView,x:Number.isFinite(value?.x)?value!.x!:0,y:Number.isFinite(value?.y)?value!.y!:0,rotation:Number.isFinite(value?.rotation)?value!.rotation!%360:0,rulers:!!value?.rulers,grid:!!value?.grid,snap:!!value?.snap,gridSize:Number.isFinite(value?.gridSize)?Math.max(1,Math.min(10000,value!.gridSize!)):100,units,resolution:Number.isFinite(value?.resolution)?Math.max(1,Math.min(2400,value!.resolution!)):72,rulerOrigin:{x:Number.isFinite(origin?.x)?origin!.x:0,y:Number.isFinite(origin?.y)?origin!.y:0},guides:Array.isArray(value?.guides)?value.guides.filter(g=>g&&typeof g.id==='string'&&(g.axis==='x'||g.axis==='y')&&Number.isFinite(g.position)&&Math.abs(g.position)<=16384).slice(0,100):[]};}
export function documentPoint(clientX:number,clientY:number,rect:{left:number;top:number;width:number;height:number},w:number,h:number,zoom:number,view:EditorView){const x=clientX-rect.left-rect.width/2-view.x,y=clientY-rect.top-rect.height/2-view.y,r=-view.rotation*Math.PI/180,s=zoom/100;return{x:(x*Math.cos(r)-y*Math.sin(r))/s+w/2,y:(x*Math.sin(r)+y*Math.cos(r))/s+h/2};}
export function fitZoom(w:number,h:number,areaW:number,areaH:number,rotation:number){const r=rotation*Math.PI/180,bw=Math.abs(w*Math.cos(r))+Math.abs(h*Math.sin(r)),bh=Math.abs(w*Math.sin(r))+Math.abs(h*Math.cos(r));return clampZoom(Math.min((areaW-80)/bw,(areaH-80)/bh)*100);}
export function snapPosition(value:number,axis:'x'|'y',extent:number,zoom:number,view:EditorView){if(!view.snap)return value;const targets=[0,extent/2,extent,...view.guides.filter(g=>g.axis===axis).map(g=>g.position)];if(view.grid)targets.push(Math.round(value/view.gridSize)*view.gridSize);let nearest=value,distance=6/(zoom/100);for(const target of targets)if(Math.abs(target-value)<distance){nearest=target;distance=Math.abs(target-value)}return nearest;}
